### PR TITLE
fix: removed outdated regex

### PR DESCRIPTION
**Pull request by JTaeuber**
## Motivation
Relates to https://github.com/caas-team/sparrow/issues/80

## Changes
Removed outdated regex tag.

For additional information look at the commits.

## TODO

- [x] I've assigned this PR to myself
- [x] I've labeled this PR correctly

### CODE REVIEW

**Comment by JTaeuber** [comment]
Please also take a look at these images in the sparrow package and delete them manually if needed.
image

**Review by lvlcn-t — APPROVED** [review]
LGTM

**Comment by lvlcn-t** [comment]
> Please also take a look at these images in the sparrow package and delete them manually if needed. image

@y-eight @NiklasTreml @puffitos Can one of you remove these images manually?

**Comment by puffitos** [comment]
> Please also take a look at these images in the sparrow package and delete them manually if needed. image

@lvlcn-t @JTaeuber images pruned

**Pull request merged**
