### PR TITLE
fix: enrich targets now accepts any scheme

### LINKED ISSUE #148: Bug: DNS Check can never use targets supplied by target manager
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, targets supplied by targetmanager to the dns check fail the validation and cannot be registered. This is because the targets include a scheme like http or https, which the dns checks config validation will reject.

### Expected Behavior

Sparrow should "just work", i.e. just parse the url and throwaway everything that is not the domain name

### Steps To Reproduce

1. Run sparrow with targetmanager enabled and configured.
2. Configure a dns check
3. Add a targetmanager remote target with a https scheme
4. Check logs

### Relevant logs and/or screenshots, environment information, etc.

```console
{"time":"2024-06-06T13:19:38.257569916Z","level":"ERROR","source":{"function":"github.com/caas-team/sparrow/pkg/sparrow.(*ChecksController).Reconcile","file":"/home/runner/work/sparrow/sparrow/pkg/sparrow/controller.go","line":100},"msg":"Failed to create checks from config","error":"invalid configuration field \"targets\" in check \"dns\": target URLs must not start with 'https://' or 'http://'"} 
```

### Who can address the issue?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by niklastreml**
## Motivation

Closes #148 

This improves the logic in `enrichTargets` to account for any scheme, be that http, https, tcp whatever floats your boat, as long as it's a valid url we're happy.

## Changes

Parse the url into a `net.Url` so we grab the dns name in an easier way for the dns check.

For additional information look at the commits.

## Tests done
I've tested it with the latency and dns check enabled using mixed set of targets configured with HTTP and  HTTPS. Seemed to work fine

- [x] Unit tests succeeded
- [x] E2E tests succeeded

## TODO

- [x] I've assigned this PR to myself
- [x] I've labeled this PR correctly

### CODE REVIEW

**Review by lvlcn-t — COMMENTED** [review]
LGTM but could you add some unit tests for the cases this PR is supposed to fix?

Additionally we should investigate why this test sometimes fails:
```log
=== RUN   Test_gitlabTargetManager_Reconcile_Registration_Update
{"time":"2024-06-06T16:34:19.377725874Z","level":"INFO","source":{"function":"github.com/caas-team/sparrow/pkg/sparrow/targets.(*manager).Reconcile","file":"/home/runner/work/sparrow/sparrow/pkg/sparrow/targets/manager.go","line":82},"msg":"Starting target manager reconciliation"}
{"time":"2024-06-06T16:34:19.388429797Z","level":"INFO","source":{"function":"github.com/caas-team/sparrow/pkg/sparrow/targets/remote/test.(*MockClient).PostFile","file":"/home/runner/work/sparrow/sparrow/pkg/sparrow/targets/remote/test/remotemock.go","line":53},"msg":"MockPostFile called","err":null}
{"time":"2024-06-06T16:34:19.478009469Z","level":"INFO","source":{"function":"github.com/caas-team/sparrow/pkg/sparrow/targets/remote/test.(*MockClient).FetchFiles","file":"/home/runner/work/sparrow/sparrow/pkg/sparrow/targets/remote/test/remotemock.go","line":62},"msg":"MockFetchFiles called","targets":1,"err":null}
{"time":"2024-06-06T16:34:19.478098907Z","level":"INFO","source":{"function":"github.com/caas-team/sparrow/pkg/sparrow/targets/remote/test.(*MockClient).PutFile","file":"/home/runner/work/sparrow/sparrow/pkg/sparrow/targets/remote/test/remotemock.go","line":44},"msg":"MockPutFile called","err":null}
{"time":"2024-06-06T16:34:19.578621783Z","level":"INFO","source":{"function":"github.com/caas-team/sparrow/pkg/sparrow/targets/remote/test.(*MockClient).FetchFiles","file":"/home/runner/work/sparrow/sparrow/pkg/sparrow/targets/remote/test/remotemock.go","line":62},"msg":"MockFetchFiles called","targets":1,"err":null}
{"time":"2024-06-06T16:34:19.578713224Z","level":"INFO","source":{"function":"github.com/caas-team/sparrow/pkg/sparrow/targets/remote/test.(*MockClient).PutFile","file":"/home/runner/work/sparrow/sparrow/pkg/sparrow/targets/remote/test/remotemock.go","line":44},"msg":"MockPutFile called","err":null}
{"time":"2024-06-06T16:34:19.678783951Z","level":"INFO","source":{"function":"github.com/caas-team/sparrow/pkg/sparrow/targets/remote/test.(*MockClient).FetchFiles","file":"/home/runner/work/sparrow/sparrow/pkg/sparrow/targets/remote/test/remotemock.go","line":62},"msg":"MockFetchFiles called","targets":1,"err":null}
{"time":"2024-06-06T16:34:19.678915467Z","level":"INFO","source":{"function":"github.com/caas-team/sparrow/pkg/sparrow/targets/remote/test.(*MockClient).PutFile","file":"/home/runner/work/sparrow/sparrow/pkg/sparrow/targets/remote/test/remotemock.go","line":44},"msg":"MockPutFile called","err":null}
    manager_test.go:457: Reconcile() should have updated the registration twice
--- FAIL: Test_gitlabTargetManager_Reconcile_Registration_Update (0.30s)
```

**Comment by niklastreml** [comment]
as far as the flaky test goes, I don't have time to look into it, but I'll file a bug report

**Review by lvlcn-t — APPROVED** [review]
LGTM

**Comment by niklastreml** [comment]
Created the issue #150

**Pull request merged**
